name: Build and Deploy Mkdocs
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish-readthedocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull Changes
        run: git pull

      - name: Install Mkdocs
        run: pip install mkdocs mkdocs-material pymdown-extensions py-dot 

      - name: Deploy site
        run: mkdocs gh-deploy --strict
